/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DealRouteImport } from './routes/deal'
import { Route as IndexRouteImport } from './routes/index'

const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DealRoute = DealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deal' | '/inbox' | '/kanban'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deal' | '/inbox' | '/kanban'
  id: '__root__' | '/' | '/deal' | '/inbox' | '/kanban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealRoute: typeof DealRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal': {
      id: '/deal'
      path: '/deal'
      fullPath: '/deal'
      preLoaderRoute: typeof DealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealRoute: DealRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
