/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DealRouteImport } from './routes/deal'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationsNewRouteImport } from './routes/automations.new'

const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DealRoute = DealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsNewRoute = AutomationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/automations/new': typeof AutomationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/automations/new': typeof AutomationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/deal': typeof DealRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/automations/new': typeof AutomationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/deal'
    | '/inbox'
    | '/kanban'
    | '/automations/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automations' | '/deal' | '/inbox' | '/kanban' | '/automations/new'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/deal'
    | '/inbox'
    | '/kanban'
    | '/automations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRouteWithChildren
  DealRoute: typeof DealRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal': {
      id: '/deal'
      path: '/deal'
      fullPath: '/deal'
      preLoaderRoute: typeof DealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/new': {
      id: '/automations/new'
      path: '/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof AutomationsNewRouteImport
      parentRoute: typeof AutomationsRoute
    }
  }
}

interface AutomationsRouteChildren {
  AutomationsNewRoute: typeof AutomationsNewRoute
}

const AutomationsRouteChildren: AutomationsRouteChildren = {
  AutomationsNewRoute: AutomationsNewRoute,
}

const AutomationsRouteWithChildren = AutomationsRoute._addFileChildren(
  AutomationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRouteWithChildren,
  DealRoute: DealRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
